katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

# TODO: Implement Routings Here

todolist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user 
from todolist.views import logout_user
from todolist.views import create_task 
from todolist.views import delete_task
from todolist.views import complete_task
from todolist.views import show_test
from todolist.views import show_data_json

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='todolist'),
    path('test/', show_test, name='test'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add/', create_task, name='add'),
    path('delete_task/<int:id>', delete_task, name='delete_task_id'),
    path('complete_task/<int:id>', complete_task, name='complete_task_id'),
    path('json/', show_data_json, name='show_data_json'),
]

todolist/models.py
from gc import is_finalized
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/views.py
from django.shortcuts import render
from todolist.models import Task
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    # data_todolist_item = Task.objects.filter(user = request.user)

    context = {
        # 'list_item' : data_todolist_item,
        'user' : request.user,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

def show_test(request):
    return render(request, 'test.html')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login')

    context = {'form':form}
    return render(request, 'register.html', context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        if title != "" and description != "":
            data = Task.objects.create(user=request.user, title=title, description=description, date=datetime.datetime.today())
            return JsonResponse({
                    "pk": data.id,
                    "fields": {
                        "title": data.title,
                        "description": data.description,
                        "is_finished": data.is_finished,
                        "date": data.date,
                    },
                },
                status=200,
            )
        else:
            messages.info(request, 'Please fill the title/description!')

    context = {}    
    return render(request, 'createtask.html', context)

@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    selected = Task.objects.get(user = request.user, id=id)
    selected.delete()
    return redirect('todolist:todolist')

@login_required(login_url='/todolist/login/')
def complete_task(request, id):
    selected = Task.objects.get(user = request.user, id=id)
    selected.is_finished = not selected.is_finished
    selected.save()
    return redirect('todolist:todolist')

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')

    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/todolist/login/')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def show_data_json(request):
    data = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/templates/createtask.html
{% extends 'test.html' %}

{% block meta %}
<title>Create a New Task</title>
{% endblock meta %}

{% block content %}

<body>
    <section class="bg-[#87BCF2] min-h-screen flex flex-row items-center justify-center">

        <div class="bg-[#F3F5F9] flex rounded-2xl shadow-2xl shadow-blue-500 max-w-3xl p-5 items-center">
            <div class=" px-8">
                <div class="flex flex-row">
                    <h2 class="font-bold sm:text-3xl text-lg">Tell us what you're up to</h2>
                    <h2 class="font-extrabold sm:text-3xl text-lg text-[#0951A8]">.</h2>
                </div>
                <p class="text-sm mt-2">Add one of your to-do for today!</p>
                <form method="POST" action="" class="flex flex-col">
                    {% csrf_token %}
                    <input class="p-2 mt-4 mb-3 rounded-xl border border-white" type="text" name="title" placeholder="Title">
                    <p class="text-sm mb-2">Describe your task</p>
                        <textarea class="rounded-xl border text-black border-white mb-5" name="description"></textarea>
                    <button class="bg-[#0951A8] shadow-md mb-3 shadow-blue-500/50 rounded-xl text-white py-2 hover:scale-110 duration-500">New task</button>
                </form>
                {% if messages %}
            <ul>
                {% for message in messages %}
                    <li class="mt-4 text-center text-sm">{{ message }}</li>
                {% endfor %}
            </ul>
    {% endif %}
                <div class="mt-4 grid grid-cols-3 items-center text-gray-500">
                    <hr class="border-gray-500">
                    <p class="text-center items-center">OR</p>
                    <hr class="border-gray-500">
                </div>
                <div>
                    <button class="bg-white w-full rounded-xl text-gray-600 text-md py-2 mt-4 border hover:scale-110 duration-500">
                        <a href="{% url 'todolist:todolist' %}">
                            Go back
                        </a></button>
                </div>
            </div>
            
            <!-- <div class="sm:block hidden w-1/2">
                <img class="rounded-2xl object-cover h-96 w-80" src="https://cdn.discordapp.com/attachments/870380505021968385/1027321829641179166/isometric-checklist-to-do-list-clipboard-checklist-project-management-planning-keeping-score-completed-tasks-155265371.jpeg">
            </div>
        </div> -->


        <!-- <div class="flex flex-row mt-8 text-3xl">
            <h1 class="font-normal  text-[#F3F5F9]">anywhere</h1>
            <h1 class="font-extrabold text-[#FF0076]">.&nbsp;</h1>
            <h1 class="font-normal text-[#F3F5F9]">anytime</h1>
            <h1 class="font-extrabold text-[#FF0076]">.&nbsp;</h1>
            <h1 class="font-normal text-[#F3F5F9]">your&nbsp;</h1>
            <h1 class="font-semibold text-[#FF0076]">to-do's</h1>
        </div> -->
        
    </section>
</body>

{% endblock content %}

todolist/templates/createtask_test.html
{% extends 'base.html' %}

{% block meta %}
<title>Create a New Task</title>
{% endblock meta %}

{% block content %}

<div class = "task">

    <h1>Create a New Task</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Title: </td>
                <td><input type="text" name="title" placeholder="Title" class="form-control"></td>
            </tr>

            <tr>
                <td>Description: </td>
                <td><input type="textarea" name="description" placeholder="Description" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn create_btn" type="submit" value="Create Task"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <br>
    Want to go back to the list? <a href="{% url 'todolist:todolist' %}">Go Back</a>

</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'test.html' %}

{% block meta %}
<title>Task Manager</title>
{% endblock meta %}


{% block content %}

<body>
    <section class="bg-[#87BCF2] min-h-screen flex flex-col items-center justify-center">

        <div class="bg-[#F3F5F9] flex rounded-2xl shadow-2xl shadow-blue-500 max-w-3xl p-5 items-center">
            <div class="sm:w-1/2 px-8">
                <div class="flex flex-row">
                    <h2 class="font-bold text-3xl">Login</h2>
                    <h2 class="font-extrabold text-3xl text-[#0951A8]">.</h2>
                </div>
                <p class="text-sm mt-2">Access your own Task Manager now</p>
                <form method="POST" action="" class="flex flex-col gap-4">
                    {% csrf_token %}
                    <input class="p-2 mt-4 rounded-xl border border-white" type="text" name="username" placeholder="Username">
                    <input class="p-2 rounded-xl border border-white" type="password" name="password" placeholder="Password">
                    <button class="bg-[#0951A8] shadow-md shadow-blue-500/50 rounded-xl text-white py-2 hover:scale-110 duration-500">Login</button>
                </form>
                {% if messages %}
            <ul>
                {% for message in messages %}
                    <li class="mt-4 text-center text-sm">{{ message }}</li>
                {% endfor %}
            </ul>
    {% endif %}
                <div class="mt-4 grid grid-cols-3 items-center text-gray-500">
                    <hr class="border-gray-500">
                    <p class="text-center items-center">OR</p>
                    <hr class="border-gray-500">
                </div>
                <div>
                    <button class="bg-white w-full rounded-xl text-gray-600 text-sm py-2 mt-4 border hover:scale-110 duration-500">
                        <a href="{% url 'todolist:register' %}">
                            Create an Account
                        </a></button>
                </div>
            </div>
            <div class="sm:block hidden w-1/2">
                <img class="rounded-2xl object-cover h-96 w-80" src="https://cdn.discordapp.com/attachments/870380505021968385/1027321829641179166/isometric-checklist-to-do-list-clipboard-checklist-project-management-planning-keeping-score-completed-tasks-155265371.jpeg">
            </div>
        </div>


        <div class="flex flex-row mt-8 md:text-3xl text-lg">
            <h1 class="font-normal  text-[#F3F5F9]">anywhere</h1>
            <h1 class="font-extrabold text-[#FF0076]">.&nbsp;</h1>
            <h1 class="font-normal text-[#F3F5F9]">anytime</h1>
            <h1 class="font-extrabold text-[#FF0076]">.&nbsp;</h1>
            <h1 class="font-normal text-[#F3F5F9]">your&nbsp;</h1>
            <h1 class="font-semibold text-[#FF0076]">to-do's</h1>
        </div>
        
    </section>
</body>
</html>

{% endblock content %}

todolist/templates/login_test.html
{% extends 'base.html' %}

{% block meta %}
<title>Task Manager</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Welcome to the Task Manager</h1>

    <h2>Login</h2>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Don't have an account? <a href="{% url 'todolist:register' %}">Create Account</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'test.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}


{% block content %}
<body class="bg-[#87BCF2]">
    <section class="bg-[#87BCF2] min-h-screen flex flex-row items-center sm:object-scale-down sm:h-full sm:w-full h-full w-[550px]">
        <div class=>
            <div class="flex flex-row mx-10">
                <h1 class="text-[#F3F5F9] text-4xl font-bold">Create a new account</h1>
                <h1 class="text-[#0951A8] text-4xl font-bold">.</h1>
            </div>
            
            <div class="flex flex-row mx-10 mb-3">
                <p class="text-black text-lg font-semibold">Already a member?</p>
                <a class="text-[#276FC8] text-lg font-medium" href="{% url 'todolist:login' %}">&nbsp;Login</a>
            </div>
        <div class="bg-[#F3F5F9] rounded-2xl items-center mx-10 p-10">
                <form method="POST">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                        <tr>
                            <td></td>
                            <td>
                            <button class="bg-[#0951A8] shadow-sm shadow-blue-500 p-[70px] rounded-xl text-sm py-3 mt-4 hover:scale-110 duration-500">
                                <input class="text-white text-lg font-medium" type="submit" name="submit" value="Register"/></td>
                            </button>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
        <div class="p-5 items-center text-center">
            <div>
                <h1>
                    
                </h1>
            </div>
        </div>
    </section>
</body>
{% endblock content %}

todolist/templates/register_test.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}

<div class = "login">
    <h1>Registration Form</h1>

        <form method="POST" >
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register"/></td>
                </tr>
            </table>
        </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}

todolist/templates/test.html
{% load tailwind_tags %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}
    {% endblock meta %}
    {% tailwind_css %}
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>

todolist/templates/todolist.html
{% extends 'test.html' %}
{% block meta %}
<title>
    Your Todolist
</title>
{% endblock meta %}
{% block content %}

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <div id="create_modal" class="fixed w-full min-h-screen items-center justify-center  z-50 inset-0 hidden">
        <div class="bg-[#F3F5F9] flex rounded-2xl shadow-2xl shadow-blue-500 max-w-3xl p-5 items-center">
            <div class="px-8">
                <div class="flex flex-row">
                    <h2 class="font-bold sm:text-3xl text-lg">Tell us what you're up to</h2>
                    <h2 class="font-extrabold sm:text-3xl text-lg text-[#0951A8]">.</h2>
                </div>
                <p class="text-sm mt-2">Add one of your to-do for today!</p>
                <form method="POST" action="" class="flex flex-col" id="task_form">
                    {% csrf_token %}
                    <input class="p-2 mt-4 mb-3 rounded-xl border border-white" id="title" type="text" name="title" placeholder="Title">
                    <p class="text-sm mb-2">Describe your task</p>
                        <textarea class="rounded-xl border text-black border-white mb-5" id="description" name="description"></textarea>
                    <button id="add_task" class="bg-[#0951A8] shadow-md mb-3 shadow-blue-500/50 rounded-xl text-white py-2 hover:scale-110 duration-500">New task</button>
                </form>
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li class="mt-4 text-center text-sm">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <div class="mt-4 grid grid-cols-3 items-center text-gray-500">
                    <hr class="border-gray-500">
                    <p class="text-center items-center">OR</p>
                    <hr class="border-gray-500">
                </div>
                <div>
                    <button class="bg-white w-full rounded-xl shadow-md shadow-gray-400 text-gray-600 text-md py-2 mt-4 border hover:scale-110 duration-500">
                        <a id="close_new_task">
                            Go back
                        </a></button>
                </div>
            </div>
        </div>
    </div>
    <nav class="bg-[#87BCF2] drop-shadow-lg shadow-[#BCDBFB] border-gray-200 px-2 sm:px-3 py-4 rounded">
        <div class="container flex flex-wrap justify-between items-center mx-auto">
            <a href="" class="flex items-center">
                <span class="self-center text-2xl font-bold whitespace-nowrap">{{user}}'s Task Manager</span>
            </a>
            <button class="bg-white py-3 px-8 rounded-2xl shadow-2xl font-medium "><a href="{% url 'todolist:logout' %}">Logout</a></button>
    </nav>
    <section class="bg-[#F3F5F9] min-h-screen justify-center items-center">
        <div class="flex flex-col text-center">
            <div class="p-4 my-5">
                <h3 class="font-medium text-xl">Welcome back, {{user}}!</h3>
            </div>
            <!-- CARD -->
            <div class="flex flex-wrap flex-row justify-center" id="yourtodolist">
            </div>
            <!-- END OF CARD -->
            <div class="mt-5 p-4">
                <button class="bg-white p-4 px-8 rounded-2xl shadow-2xl"><a id="new_task">+ New Task</a></button>
            </div>
        </div>
        
        <br>
    </section>
</body>

<script>
    $(document).ready(function(){
        let modal = document.querySelector("#create_modal")
        let openButton = document.querySelector("#new_task")
        let closeButton = document.querySelector("#close_new_task")
        let card = (data) => 
        `
            <div>
                <div id=${data.pk} class="w-80 mx-5 bg-white shadow-2xl rounded-lg overflow-hidden group">
                    <img src="https://cdn.discordapp.com/attachments/870380505021968385/1027314161698492456/example.jpeg">
                    <div class="py-4 px-5 text-center">
                        <p class="text-[#FF0076] uppercase tracking-wide font-bold text-sm">
                            ${data.fields.date}
                        </p>
                        <h1 class="text-gray-800 uppercase tracking-wide font-bold text-2xl">
                            ${data.fields.title}
                        </h1>
                        <p class="text-sm tracking-wide text-gray-500 my-4">
                            ${data.fields.description}
                        </p>
                        ${data.fields.is_finished ? `<h1 class="bg-green-600 shadow-sm shadow-green-500 text-white p-3 rounded-2xl uppercase tracking-wide font-bold text-2xl">
                            Finished
                        </h1>` : `<h1 class="bg-[#BCDBFB] shadow-sm shadow-[#BCDBFB] text-[#87BCF2] p-3 rounded-2xl uppercase tracking-wide font-bold text-2xl">
                            Not Finish
                        </h1>`}
                    </div>
                    <div class="items-center justify-center bg-[#276FC8] text-center h-0 group-hover:h-16 transition-all duration-300">
                            <div class="text-[#276FC8] p-[14px] items-center">
                                <button class="bg-white rounded-2xl p-2 text-[14px] mx-3 mr-5 font-normal grow" onclick="location.href='complete_task/${data.pk}'">Change Status</button>  
                                <button class="bg-white rounded-2xl p-2 text-[14px] mx-3 font-normal grow" onclick="location.href='delete_task/${data.pk}'">Delete Task</button> 
                            </div>
                    </div>
                </div>
            </div>
        </div>
        `;

        function add_task(e){
            $("#yourtodolist").append(card(e));
        }

        openButton.addEventListener("click", () =>
        {
            modal.classList.remove("hidden");
            modal.classList.add("flex");
        });

        closeButton.addEventListener("click", () =>
        {
            modal.classList.remove("flex");
            modal.classList.add("hidden");
            reset();
        });

        function show_tasks(){
            $.get("{% url 'todolist:show_data_json' %}", function(e){
                $.each(e, function(i, result) {
                    add_task(result)
                });
            });
        };
        
        function reset(){
            $("#task_form").trigger("reset");
        }

        $("#task_form").submit((event) => {
            event.preventDefault();
            if ($("#title").val() && $("#description").val()) {
                $.ajax({
                type: "POST",
                url: "{% url 'todolist:add' %}",
                data: {title: $("#title").val(), description: $("#description").val()},
                headers: {"X-CSRFToken": document.querySelector("[name=csrfmiddlewaretoken]").value},
                success: function(result) {
                    modal.classList.remove("flex");
                    modal.classList.add("hidden");
                    reset();
                    add_task(result);
                },
                });
            } else {
                alert("Please fill the title/description!");
            }
            });

        show_tasks();
    });
</script>

{% endblock content %}

todolist/templates/todolist_test.html
{% extends 'base.html' %}

{% block content %}
<h1>Your Task Manager</h1>

<h3>Welcome, {{user}}!</h3>

<table>
    <tr>
    <th>Date</th>
    <th>Title</th>
    <th>Description</th>
    <th>Finished</th>
    </tr>
    {% comment %} Add data below {% endcomment %}
    {% for item in list_item %}
        <tr>
            <td>{{item.date}}</td>
            <td>{{item.title}}</td>
            <td>{{item.description}}</td>
            <td>
                {% if item.is_finished %}
                Yes
                <input type="checkbox" onclick="location.href=`{% url 'todolist:complete_task_id' item.id %}`" checked/>
                {% else %}
                No
                <input type="checkbox" onclick="location.href=`{% url 'todolist:complete_task_id' item.id %}`"/>
                {% endif %}
            </td>
            <td>
                <button><a href="{% url 'todolist:delete_task_id' item.id %}">Delete Task</a></button>
            </td>
        </tr>
    {% endfor %}
</table>
<br>
<button><a href="{% url 'todolist:create_task' %}">New Task</a></button>
<button><a href="{% url 'todolist:logout' %}">Logout</a></button>

{% endblock content %}